### PR TITLE
Add option for Breakdown on Special Cases

### PR DESCRIPTION
**Pull request by Cyborger1**
Defaults to `false` in the config

### CODE REVIEW

**Comment by Ferrariic** [comment]
Will review this shortly

**Comment by Ferrariic** [comment]
Option off (default)
image

Option on 
image

This works as intended -- approved

**Review by Ferrariic — APPROVED** [review]

**Comment by Cyborger1** [comment]
Don't merge this yet, I want to explore https://github.com/Bot-detector/Bot-Detector-Core-Files/issues/441 as an alternative to this.

**Comment by Cyborger1** [comment]
Just pointing out with these changes that using the "breakdown" parameter is redundant with the checks I put in place, but saving a bit on server bandwidth is always a plus I suppose.

**Review by Ferrariic — APPROVED** [review]

**Comment by Ferrariic** [comment]
I've verified that this works.

**Pull request merged**
